sudo: required
services: 
  - docker

script:
  - docker build -t mannydesign/ci_cd .
  - docker images mannydesign/ci_cd 

before_deploy:
  - docker login -u  --password-stdin 

deploy:
  provider: script 
  script: docker push mannydesign/ci_cd
  on:
    branch: master
